name: Job Concurrecy Workflow 

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: "*/1 * * * *"
  #   push
#concurrency: 
env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Debug username
              run: echo DOCKER_USERNAME is ${{ vars.DOCKER_USERNAME }}

            - name: Docker Build
              run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

            - name: Docker Login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    deploy:
        needs: docker
        concurrency: 
          group: production-deployment
          cancel-in-progress: false
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              timeout-minutes: 1
              run: |
                echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
                sleep 6000s
              